<?php

$dataset = array(
    'sato' => array(
        'apple'  => 2.5,
        'banana' => 3.5,
        'grape'  => 3.0,
        'melon'  => 3.5,
        'orange' => 2.5,
        'peach'  => 3.0
    ),
    'suzuki' => array(
        'apple'  => 3.0,
        'banana' => 3.5,
        'grape'  => 1.5,
        'melon'  => 5.0,
        'peach'  => 3.0,
        'orange' => 3.5
    ),
    'takahashi'=> array(
        'apple'  => 2.5,
        'banana' => 3.0,
        'melon'  => 3.5,
        'peach'  => 4.0
    ),
    'tanaka'=> array(
        'banana' => 3.5,
        'grape'  => 3.0,
        'peach'  => 4.5,
        'melon'  => 4.0,
        'orange' => 2.5
    ),
    'itou'=> array(
        'apple'  => 3.0,
        'banana' => 4.0,
        'grape'  => 2.0,
        'melon'  => 3.0,
        'peach'  => 3.0,
        'orange' => 2.0
    ),
    'watanabe'=> array(
        'apple'  => 3.0,
        'banana' => 4.0,
        'peach'  => 3.0,
        'melon'  => 5.0,
        'orange' => 3.5
    ),
    'yamamoto'=> array(
        'banana' => 4.5,
        'orange' => 1.0,
        'melon'  => 4.0
    )
);
